In [2]:
!pip install statsmodels

In [9]:
from statsmodels.stats.weightstats import ztest as ztest
import numpy as np
from scipy import stats

# enter IQ levels for 20 patients

data= [88,92,94,96,97,97,97,99,99,105,109,109,109,110,112,112,112,113,114,115]

print(np.mean(data))

ztest_stats,p_value=ztest(data,value=100)

103.95


In [11]:
print(ztest_stats)
print(p_value)
alpha=0.05
if p_value<=alpha:
    print("Reject")
else:
    print("Accept")

2.0826322021483703
0.03728476161171385
Reject


In [13]:
# t-test
ages=[10,20,35,50,28,40,55,18,16,55,30,25,43,18,30,28,14,24,16,17,32,35,26,27,65,18,43,23,21,20,19,70]


In [14]:
import numpy as np
ages_mean = np.mean(ages)
ages_mean

30.34375

In [15]:
sample_size = 10
age_sample=np.random.choice(ages,sample_size)

In [16]:
age_sample

array([55, 30, 35, 30, 40, 43, 20, 16, 43, 10])

In [17]:
np.mean(age_sample)

32.2

In [22]:
from scipy.stats import ttest_1samp

In [23]:
s,p=ttest_1samp(age_sample,45)
if p<=0.5:
    print("Rejected")
else:
    print("Accepted")

Rejected


In [24]:
ttest_1samp(age_sample,31)

Ttest_1sampResult(statistic=0.27326101682114856, pvalue=0.7908196891315389)

In [25]:
ttest_1samp(age_sample,28)

Ttest_1sampResult(statistic=0.9564135588740184, pvalue=0.3638468103605259)

In [27]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import math
np.random.seed(10)
school_ages=stats.poisson.rvs(mu=30, size=2000)
classA_ages=stats.poisson.rvs(mu=35, size=80)

In [28]:
school_ages

array([35, 32, 30, ..., 24, 19, 30], dtype=int64)

In [29]:
classA_ages

array([33, 27, 26, 31, 35, 37, 37, 36, 29, 50, 44, 32, 39, 33, 32, 34, 49,
       35, 26, 34, 33, 39, 32, 36, 40, 39, 33, 29, 42, 29, 33, 38, 29, 32,
       31, 29, 26, 31, 40, 26, 41, 28, 25, 37, 25, 29, 46, 36, 46, 26, 34,
       55, 37, 29, 36, 32, 44, 27, 38, 33, 34, 36, 30, 32, 37, 32, 31, 44,
       41, 32, 26, 29, 48, 35, 32, 35, 30, 38, 27, 39], dtype=int64)

In [30]:
classA_ages.mean()

34.475

In [31]:
tstatistics,p_value=ttest_1samp(classA_ages,popmean=school_ages.mean())

In [32]:
if p_value <=0.05:
    print("Reject")
else:
    print("Accept")

Reject


In [33]:
np.random.seed(10)
classB_ages=stats.poisson.rvs(mu=32,size=60)
classB_ages.mean()

31.05

In [35]:
_,p_value=stats.ttest_ind(a=classA_ages,b=classB_ages,equal_var=False)

In [36]:
if p_value<0.05: #alpha value is 0.05 or 5%
    print("We are rejecting null hypothesis: classes are same,dependent")
else:
    print("We are accepting null hypothesis: classes are different, independent")

We are rejecting null hypothesis: classes are same,dependent


In [40]:
weight1=[25,30,28,34,26,28,32,31,30,45]
weight2=weight1+stats.norm.rvs(scale=5,loc=-1.25,size=10)

In [41]:
print(weight1)
print(weight2)

[25, 30, 28, 34, 26, 28, 32, 31, 30, 45]
[22.56497908 29.03642575 23.21464276 35.48332419 29.46250204 11.85201614
 36.84074425 29.46739638 31.05444226 47.06187006]


In [44]:
weight_df=pd.DataFrame({"weight_10":np.array(weight1),
                       "weight_20":np.array(weight2),
                       "weight_change":np.array(weight2)-np.array(weight1)})

In [45]:
_,p_value=stats.ttest_rel(a=weight1,b=weight2)

In [46]:
print(p_value)

0.5085427016179156


In [47]:
if p_value<0.05:
    print("We are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

we are accepting null hypothesis
